name: Publish esp-idf-5 (esp32) image

on:
  workflow_dispatch:
    inputs:
      esp_idf_version:
        description: 'ESP-IDF version'
        required: false
        default: '5.0.2'
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/publish-esp-idf-5.yml"
      - "tools/build-ports/esp32/Dockerfile"

permissions:
  packages: write

env:
  ESP_IDF_VERSION: "${{ github.event.inputs.esp_idf_version || '5.0.2' }}"

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the docker image with ESP-IDF version ${{ env.ESP_IDF_VERSION }}
        run: |
          tag=ghcr.io/hwinther/lanot/esp-idf-5:${{ env.ESP_IDF_VERSION }}
          tag_latest=ghcr.io/hwinther/lanot/esp-idf-5:latest
          echo tag=$tag tag_latest=$tag_latest
          docker build tools/build-ports/esp32 --build-arg ESP_IDF_VERSION=v${{ env.ESP_IDF_VERSION }} -t $tag -t $tag_latest -f tools/build-ports/esp32/Dockerfile
          docker push $tag
          docker push $tag_latest