name: Publish esp-open-sdk (esp8266) image

on:
  workflow_dispatch:
    inputs:
      vendor_sdk_version:
        description: 'Vendor SDK version'
        required: false
        default: '2.1.0'
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/publish-esp-open-sdk.yml"
      - "tools/build-ports/esp8266/Dockerfile"

permissions:
  # for ghcr.io (docker registry):
  packages: write

env:
  VENDOR_SDK_VERSION: "${{ github.event.inputs.vendor_sdk_version || '2.1.0' }}"

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the docker image with vendor SDK version ${{ env.VENDOR_SDK_VERSION }}
        run: |
          git clone --recursive https://github.com/hwinther/esp-open-sdk.git

          tag=ghcr.io/hwinther/lanot/esp-open-sdk:$VENDOR_SDK_VERSION
          tag_latest=ghcr.io/hwinther/lanot/esp-open-sdk:latest
          docker build esp-open-sdk --build-arg MAKE_ARGS="VENDOR_SDK=$VENDOR_SDK_VERSION" -t $tag -t $tag_latest -f esp-open-sdk/Dockerfile
          docker push $tag
          docker push $tag_latest