name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Run build script
        run: |
          rm -f deploy/micropython/esp*/*
          rm -f deploy/micropython/wipy/*/*
          cd tools
          chmod +x micropython-make.sh
          ./micropython-make.sh
          find ../deploy/micropython/ -type f -exec ls -lh {} \;

      - name: Prepare distribution folder
        run: |
          mkdir -p dist
          find deploy/micropython -type f -name "*.bin" | while read file; do
            cp "$file" dist/
          done

          nodemcu32s=$(ls dist/NODEMCU32S-*.bin 2>/dev/null | head -n1)
          if [ -n "$nodemcu32s" ]; then
            nodemcu32s_name=$(basename "$nodemcu32s")
            cat >> dist/ESP32_NODEMCU32S_write_flash.cmd << EOL
          python -m esptool --chip esp32 --port %1 --baud 921600 --before default_reset --after hard_reset write_flash -z 0x1000 $nodemcu32s_name
          EOL
          fi

          nodemcuesp12e=$(ls dist/NODEMCUESP12E-*.bin 2>/dev/null | head -n1)
          if [ -n "$nodemcuesp12e" ]; then
            nodemcuesp12e_name=$(basename "$nodemcuesp12e")
            cat >> dist/ESP8266_NODEMCUESP12E_write_flash.cmd << EOL
          python -m esptool --chip esp8266 --port %1 --baud 921600 --before default_reset --after hard_reset write_flash --verify --flash_size=detect --flash_mode=qio 0 $nodemcuesp12e_name
          EOL
          fi

          lolinesp32e=$(ls dist/LOLINESP32E-*.bin 2>/dev/null | head -n1)
          if [ -n "$lolinesp32e" ]; then
            lolinesp32e_name=$(basename "$lolinesp32e")
            cat >> dist/ESP8266_LOLINESP32E_write_flash.cmd << EOL
          python -m esptool --chip esp8266 --port %1 --baud 921600 --before default_reset --after hard_reset write_flash --verify --flash_size=detect --flash_mode=qio 0 $lolinesp32e_name
          EOL
          fi
          
          bootloader=$(ls dist/bootloader*.bin 2>/dev/null | head -n1)
          if [ -n "$bootloader" ]; then
            bootloader_name=$(basename "$bootloader")
            cat >> dist/WIPY_write_flash.cmd << EOL
          curl -T $bootloader_name ftp://192.168.1.250/flash/sys/mcuimg.bin --user user:password
          EOL
          fi

          ls -lh dist/
      
      - name: Upload artifacts
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: dist/*
      
      - name: Create Release
        #if: github.event_name == 'push'
        run: |
          gh release create ${{ github.ref_name }} \
            dist/* \
            --title "Release ${{ github.ref_name }}" \
            --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
